server:
  port: 8089

spring:
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:ORCL
      username: system
      password: manager

mybatis:
  mapper-locations:  classpath:mapper/*.xml
  type-aliases-package: com.hxh.jdsun.model